default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :test do
    run_tests(
      project: "StravaProfileViewer.xcodeproj",
      scheme: "StravaProfileViewer",
      devices: ["iPhone 17 Pro"],
      only_testing: [
        "StravaProfileViewerTests"
      ],
      clean: true,
      result_bundle: true,
      output_directory: "fastlane/test_output"
    )
  end
end
